[project]
name = "nonebot-plugin-test"
version = "0.2.1"
description = "NoneBot tesy"
authors = [
    {name = "KomoriDev", email = "mute231010@gmail.com"},
]
dependencies = [
    "nonebot2>=2.3.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
